export default {
  sitename: '',
  server_domain: '',
  client_domain: '',
  template: 'nohtml',
  language: 'en-GB',
  mailer: 'smtp',
  mailfrom: '',
  fromname: '',
  sendmail: '',
  smtpsecure: 'none',
  smtpport: 25,
  smtpuser: '',
  smtppass: '',
  smtphost: 'localhost',
};
