export default {
  sitename: '',
  live_site: '',
  debug: false,
  sef_rewrite: false,
  secret: '',
  error_reporting: 0,
  log_path: '',
  tmp_path: '',
  template: '',
  language: '',
  dbtype: '',
  host: '',
  user: '',
  password: '',
  db: '',
  dbprefix: '',
  mailer: '',
  mailfrom: '',
  fromname: '',
  sendmail: '',
  smtpauth: false,
  smtpsecure: '',
  smtpport: 1025,
  smtpuser: '',
  smtppass: '',
  smtphost: '',
};
