import {
  shape,
  string,
  number,
  bool,
  oneOfType,
} from 'prop-types';

export default shape({
  sitename: string,
  live_site: string,
  debug: bool,
  sef_rewrite: bool,
  secret: string,
  error_reporting: number,
  log_path: string,
  tmp_path: string,
  template: string,
  language: string,
  dbtype: string,
  host: string,
  user: string,
  password: string,
  db: string,
  dbprefix: string,
  mailer: string,
  mailfrom: string,
  fromname: string,
  sendmail: string,
  smtpauth: bool,
  smtpsecure: string,
  smtpport: oneOfType([
    string,
    number,
  ]),
  smtpuser: string,
  smtppass: string,
  smtphost: string,
});
