export default {

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',

  LOGIN_REQUIRED: 'LOGIN_REQUIRED',

  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  CURRENT_USER: 'CURRENT_USER',

  CLEAR_SEARCH: 'CLEAR_SEARCH',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',
  CHANGE_SEARCH_TYPE: 'CHANGE_SEARCH_TYPE',

  ADD_ALERT: 'ADD_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT',

  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',

  OPEN_RECOVER_PASSWORD_FORM: 'OPEN_RECOVER_PASSWORD_FORM',
  CLOSE_RECOVER_PASSWORD_FORM: 'CLOSE_RECOVER_PASSWORD_FORM',

  RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',

  CHANGE_EMAIL_SUCCESS: 'CHANGE_EMAIL_SUCCESS',

  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAILURE: 'DELETE_ACCOUNT_FAILURE',

  SESSION_TIMEOUT: 'SESSION_TIMEOUT'
};
