// Note: these constacts can be dynamically created using a createRequestConstant method.

/*
* - BREAD Actions
*/

export const ACTORS_RESET = 'ACTORS_RESET';
export const ACTORS_BROWSE_REQUEST = 'ACTORS_BROWSE_REQUEST';
export const ACTORS_BROWSE_SUCCESS = 'ACTORS_BROWSE_SUCCESS';
export const ACTORS_BROWSE_FAILURE = 'ACTORS_BROWSE_FAILURE';

export const ACTORS_FOLLOW_REQUEST = 'ACTORS_FOLLOW_REQUEST';
export const ACTORS_FOLLOW_SUCCESS = 'ACTORS_FOLLOW_SUCCESS';
export const ACTORS_FOLLOW_FAILURE = 'ACTORS_FOLLOW_FAILURE';

export const ACTORS_UNFOLLOW_REQUEST = 'ACTORS_UNFOLLOW_REQUEST';
export const ACTORS_UNFOLLOW_SUCCESS = 'ACTORS_UNFOLLOW_SUCCESS';
export const ACTORS_UNFOLLOW_FAILURE = 'ACTORS_UNFOLLOW_FAILURE';
