
/*
* - People Actions
*/

export const PERSON_BROWSE_REQUEST = 'PERSON_BROWSE_REQUEST';
export const PERSON_BROWSE_SUCCESS = 'PERSON_BROWSE_SUCCESS';
export const PERSON_BROWSE_FAILURE = 'PERSON_BROWSE_FAILURE';

export const PERSON_READ_REQUEST = 'PERSON_READ_REQUEST';
export const PERSON_READ_SUCCESS = 'PERSON_READ_SUCCESS';
export const PERSON_READ_FAILURE = 'PERSON_READ_FAILURE';

export const PERSON_EDIT_REQUEST = 'PERSON_EDIT_REQUEST';
export const PERSON_EDIT_SUCCESS = 'PERSON_EDIT_SUCCESS';
export const PERSON_EDIT_FAILURE = 'PERSON_EDIT_FAILURE';

export const PERSON_ADD_REQUEST = 'PERSON_ADD_REQUEST';
export const PERSON_ADD_SUCCESS = 'PERSON_ADD_SUCCESS';
export const PERSON_ADD_FAILURE = 'PERSON_ADD_FAILURE';

export const PERSON_DELETE_REQUEST = 'PERSON_DELETE_REQUEST';
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';
