// Note: these constacts can be dynamically created using a createRequestConstant method.

/*
* - BREAD Actions
*/

export const PERSON_BROWSE_REQUEST = 'PERSON_BROWSE_REQUEST';
export const PERSON_BROWSE_SUCCESS = 'PERSON_BROWSE_SUCCESS';
export const PERSON_BROWSE_FAILURE = 'PERSON_BROWSE_FAILURE';

export const PERSON_READ_REQUEST = 'PERSON_READ_REQUEST';
export const PERSON_READ_SUCCESS = 'PERSON_READ_SUCCESS';
export const PERSON_READ_FAILURE = 'PERSON_READ_FAILURE';

export const PERSON_EDIT_REQUEST = 'PERSON_EDIT_REQUEST';
export const PERSON_EDIT_SUCCESS = 'PERSON_EDIT_SUCCESS';
export const PERSON_EDIT_FAILURE = 'PERSON_EDIT_FAILURE';

export const PERSON_ADD_REQUEST = 'PERSON_ADD_REQUEST';
export const PERSON_ADD_SUCCESS = 'PERSON_ADD_SUCCESS';
export const PERSON_ADD_FAILURE = 'PERSON_ADD_FAILURE';

export const PERSON_DELETE_REQUEST = 'PERSON_DELETE_REQUEST';
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';

/*
* - Social Graph Actions
*/

export const PERSON_FOLLOW_REQUEST = 'PERSON_FOLLOW_REQUEST';
export const PERSON_FOLLOW_SUCCESS = 'PERSON_FOLLOW_SUCCESS';
export const PERSON_FOLLOW_FAILURE = 'PERSON_FOLLOW_FAILURE';

export const PERSON_UNFOLLOW_REQUEST = 'PERSON_UNFOLLOW_REQUEST';
export const PERSON_UNFOLLOW_SUCCESS = 'PERSON_UNFOLLOW_SUCCESS';
export const PERSON_UNFOLLOW_FAILURE = 'PERSON_UNFOLLOW_FAILURE';
