// Note: these constacts can be dynamically created using a createRequestConstant method.

/*
* - BREAD Actions
*/

export const PEOPLE_BROWSE_REQUEST = 'PEOPLE_BROWSE_REQUEST';
export const PEOPLE_BROWSE_SUCCESS = 'PEOPLE_BROWSE_SUCCESS';
export const PEOPLE_BROWSE_FAILURE = 'PEOPLE_BROWSE_FAILURE';

export const PEOPLE_FOLLOW_REQUEST = 'PEOPLE_FOLLOW_REQUEST';
export const PEOPLE_FOLLOW_SUCCESS = 'PEOPLE_FOLLOW_SUCCESS';
export const PEOPLE_FOLLOW_FAILURE = 'PEOPLE_FOLLOW_FAILURE';

export const PEOPLE_UNFOLLOW_REQUEST = 'PEOPLE_UNFOLLOW_REQUEST';
export const PEOPLE_UNFOLLOW_SUCCESS = 'PEOPLE_UNFOLLOW_SUCCESS';
export const PEOPLE_UNFOLLOW_FAILURE = 'PEOPLE_UNFOLLOW_FAILURE';
