export const ACTOR_FOLLOW_REQUEST = 'ACTOR_FOLLOW_REQUEST';
export const ACTOR_FOLLOW_SUCCESS = 'ACTOR_FOLLOW_SUCCESS';
export const ACTOR_FOLLOW_FAILURE = 'ACTOR_FOLLOW_FAILURE';

export const ACTOR_UNFOLLOW_REQUEST = 'ACTOR_UNFOLLOW_REQUEST';
export const ACTOR_UNFOLLOW_SUCCESS = 'ACTOR_UNFOLLOW_SUCCESS';
export const ACTOR_UNFOLLOW_FAILURE = 'ACTOR_UNFOLLOW_FAILURE';

export const ACTOR_BLOCK_REQUEST = 'ACTOR_BLOCK_REQUEST';
export const ACTOR_BLOCK_SUCCESS = 'ACTOR_BLOCK_SUCCESS';
export const ACTOR_BLOCK_FAILURE = 'ACTOR_BLOCK_FAILURE';

export const ACTOR_UNBLOCK_REQUEST = 'ACTOR_UNBLOCK_REQUEST';
export const ACTOR_UNBLOCK_SUCCESS = 'ACTOR_UNBLOCK_SUCCESS';
export const ACTOR_UNBLOCK_FAILURE = 'ACTOR_UNBLOCK_FAILURE';
