export const ACTOR_FOLLOW_REQUEST = 'ACTOR_FOLLOW_REQUEST';
export const ACTOR_FOLLOW_SUCCESS = 'ACTOR_FOLLOW_SUCCESS';
export const ACTOR_FOLLOW_FAILURE = 'ACTOR_FOLLOW_FAILURE';

export const ACTOR_UNFOLLOW_REQUEST = 'ACTOR_UNFOLLOW_REQUEST';
export const ACTOR_UNFOLLOW_SUCCESS = 'ACTOR_UNFOLLOW_SUCCESS';
export const ACTOR_UNFOLLOW_FAILURE = 'ACTOR_UNFOLLOW_FAILURE';
